import Head from "next/head";
import Image from "next/image";
import styles from "../styles/Home.module.css";

export default function Home() {
	return (
		<div className={styles.container}>
			<Head>
				<title>Create Next App</title>
				<meta name="description" content="Generated by create next app" />
				<link rel="icon" href="/favicon.ico" />
			</Head>

			<main className="container w-screen flex-grow">
				<section className="w-screen h-screen flex flex-col justify-center items-center text-center">
					<h1 className="text-5xl mb-2">
						Hi👋,
						<br /> I am Sree
					</h1>

					<p className="text-xl mb-20">Full Stack Web Developer</p>
					<div className="flex w-screen justify-evenly">
						<span className="cursor-pointer hover:bg-blue-100 border-2 w-24 h-10 flex justify-center items-center rounded-lg">
							About Me
						</span>
						<span className="cursor-pointer hover:bg-blue-100 border-2 w-24 h-10 flex justify-center items-center rounded-lg">
							Projects
						</span>
						<span className="cursor-pointer hover:bg-blue-100 border-2 w-24 h-10 flex justify-center items-center rounded-lg">
							Blog
						</span>
					</div>
				</section>

				<section className="w-screen h-screen flex flex-col justify-center items-center p-5">
					<span className="text-6xl mb-2">🧑‍💻</span>
					<h1 className="text-5xl mb-2">About Me:</h1>
					<p className="text-2xl line leading-loose tracking-widest w-auto text-center">
						I am Sreemannarayana Ikkurthi🙏
						<br /> 🚀Web Developer turned Aerospace Engineer. <br />
						🖥️Love creating web appications.
						<br />
						⚡Currently helping{" "}
						<a
							href="https://www.revos.in/"
							target="_blank"
							rel="noreferrer"
							className="cursor-pointer hover:underline text-blue-700"
						>
							Revos
						</a>{" "}
						build India's largest growing
						<br /> electric vehicle charging network.
					</p>
				</section>
			</main>

			<footer className="flex justify-center mb-5">
				<span className="text-xl">Made with 💖 & 💦 by Sree</span>
			</footer>
		</div>
	);
}
